### ISSUE TITLE
INFROGRAFIA HILOS EN C#

### ISSUE THREAD

**Issue by IrvinSanchez-dev** [SistemasTecTlaxiaco/infografia-de-hilos-irvinjs22620075#2]
[INFOGRAFIA HILOS(THREADS).pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-irvinjs22620075/files/15050131/INFOGRAFIA.HILOS.THREADS.pdf)

**Comment by Kevinosorio77** [comment]
De acuerdo ala rubrica cumple con los estándares de creatividad, diseño, composición e incluye todas las indicaciones como también un buen orden y es fácilmente de comprender 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
